version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gmail
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: sql-viewer
    restart: always
    ports:
      - "8080:8080"

  app:
    image: igorkoishman/gmail-ai:latest
    container_name: gmail-ai-service
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./token.json:/app/token.json
      - ./ml_models_pro:/app/ml_models_pro

volumes:
  mysql_data:
